### ISSUE TITLE
New test post with hubpress.

### ISSUE THREAD

**Issue by Carreau** [jupyter/hubpress.io#1]
Still some bug, but seem sweet :

Not published. 
https://github.com/jupyter/hubpress.io/blob/gh-pages/_posts/2015-02-24-need-h1-to-save.adoc

Main page : 
http://jupyter.org/hubpress.io/

Login : 
http://jupyter.org/hubpress.io/hubpress

Test Post 1
http://jupyter.org/hubpress.io/2015/02/24/Test.html
Test Post 2
http://jupyter.org/hubpress.io/2015/02/24/Test.html

One of the two seem to not be listed randomly.

This is a week-old version of hubpress, (master branch) 
there seem to be a dev branch more rencent, 

It is not ready for production yet seeing the few bug there is.

**Comment by minrk** [comment]
- RSS 404s
- index doesn't appear to list any posts (seems like gh-pages issue, since served index.html doesn't look the same as the one in the repo)
- edit UI seems to be per-user (I don't see or edit posts you have written)
- If I write a post with the same name as yours on the same day, it will be clobbered silently (not a huge deal with git, I was just testing what happened with title collisions)
- every change in the title seems to result in a new copy of the file in the repo, rather than a rename

Maybe this will be a good fit in 6 months or so, but I don't think it works very well at this point.
